FROM eoitek/centos-baseos:1.9
MAINTAINER Gavin Wang <gavin.wang@eoitek.com>

RUN mkdir -p /data
COPY 05-itoaservice-1.9.1_20180514.zip /data/05-itoaservice-1.9.1_20180514.zip
WORKDIR /data
RUN unzip 05-itoaservice-1.9.1_20180514.zip